apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-backend
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
        - name: backend
          image: 779846782668.dkr.ecr.us-east-2.amazonaws.com/portfolio-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: database-2.crkkai2skkf4.us-east-2.rds.amazonaws.com
            - name: DB_USER
              value: "portfolio_user"
            - name: DB_PASSWORD
              value: "your_secure_password"
            - name: DB_NAME
              value: "portfolio_db"



# docker tag portfolio-backend:latest 779846782668.dkr.ecr.us-east-2.amazonaws.com/portfolio-backend:latest
# docker push 779846782668.dkr.ecr.us-east-2.amazonaws.com/portfolio-backend:latest

# docker tag portfolio-backend:latest 779846782668.dkr.ecr.us-east-2.amazonaws.com/portfolio-backend:latest
# docker push 779846782668.dkr.ecr.us-east-2.amazonaws.com/portfolio-backend:latest