name: Deploy Golang Backend

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to 'main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          
      - name: Set up GO ROOT
        run: |
          export GOROOT=/usr/local/go
          export PATH=$GOROOT/bin:$PATH

      - name: Install dependencies
        run: |
          cd server
          # go mod tidy

      - name: Build & Test
        run: |
          go build -o app main.go
      

      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem app ec2-user@$EC2_IP:~/backend/
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_IP "nohup ~/backend/app &"