name: Deploy React Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build React app
        run: |
          cd client
          npm install
          npm run build

      - name: Deploy to EC2
        env:
          EC2_CLIENT_IP: ${{ secrets.EC2_CLIENT_IP }}
          AWS_CLIENT_PRIVATE_KEY: ${{ secrets.AWS_CLIENT_PRIVATE_KEY }}
        run: |
          echo "$AWS_CLIENT_PRIVATE_KEY" > web-server.pem
          chmod 600 web-server.pem
          ls -la
          cd client
          scp -o StrictHostKeyChecking=no -i web-server.pem -r ./build/* ubuntu@$EC2_CLIENT_IP:/var/www/html/frontend/
          ssh -o StrictHostKeyChecking=no -i web-server.pem ubuntu@$EC2_CLIENT_IP "sudo systemctl restart nginx"