name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        cd server
        go mod tidy
        go build -o app
        
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # Write private key to file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Create directory on EC2 if it doesn't exist
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${USERNAME}@${HOST} 'mkdir -p ~/backend'
        
        # Copy the built binary and any necessary files
        cd server
        scp -o StrictHostKeyChecking=no -i ../private_key.pem \
          app \
          ${USERNAME}@${HOST}:~/backend/
        
        # Set permissions and restart service
        ssh -o StrictHostKeyChecking=no -i ../private_key.pem ${USERNAME}@${HOST} '
          chmod +x ~/backend/app
          sudo systemctl restart portfolio-app || true
        '