name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Save SSH private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem

      - name: Build Go application
        working-directory: ./server
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o app

      - name: Create remote directory
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ec2-user@${{ secrets.EC2_IP }} "mkdir -p ~/backend"

      - name: Copy binary to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ./server/app ec2-user@${{ secrets.EC2_IP }}:~/backend/

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ec2-user@${{ secrets.EC2_IP }} '
            cd ~/backend
            chmod +x app
            # Kill any existing process on port 8080
            sudo lsof -t -i:8080 | xargs -r kill -9
            # Start the application in the background
            nohup ./app > output.log 2>&1 &
            # Wait a moment to check if the process is running
            sleep 5
            if pgrep -f "./app" > /dev/null; then
              echo "Application started successfully"
            else
              echo "Failed to start application"
              cat output.log
              exit 1
            fi
          '