name: Deploy Golang Backend

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to 'main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build & Test
        run: |
          cd server
          CGO_ENABLED=0 go build -o app main.go
          # go test ./...

      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          lsof -t -i:8080 | xargs -r kill
          scp -o StrictHostKeyChecking=no -i private_key.pem server/app ec2-user@$EC2_IP:~/
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_IP "nohup ./app > output.log 2>&1 &"