name: Deploy Golang Backend

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to 'main'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build & Test
        run: |
          # cd server
          # go build -o server main.go
          go build -o main.go

      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          echo "pwd: $(pwd)"
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem server ec2-user@$EC2_IP:~/server
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$EC2_IP "nohup ~/server &"